### ISSUE TITLE
TypeError: 'NEXBeamformReader' object does not support indexing

### ISSUE THREAD

**Issue by csmibrahim** [Gi-z/CSIKit#1]
Running the code in your example

reader = NEXBeamformReader("walk_1597159475.pcap")
csi_matrix = csitools.get_CSI(reader)

I get this error 

TypeError: 'NEXBeamformReader' object does not support indexing

**Comment by Gi-z** [comment]
The included code was erroneous. Here's the correct version, I'll update this in the README too. Let me know if this works for you.

```
from CSIKit import csitools
from CSIKit import NEXBeamformReader

reader = NEXBeamformReader("walk_1597159475.pcap")
trace = reader.csi_trace
csi_matrix, no_frames, no_subcarriers = csitools.get_CSI(trace)
