### ISSUE TITLE
Ambiguous Wording in NEXCSIFrame section of Readme

### ISSUE THREAD

**Issue by CDeLeon94** [Gi-z/CSIKit#20]
https://github.com/Gi-z/CSIKit/blame/master/README.md#L191

Not clear that the link on `mzakharo` is to a PR that supports the RSSI measurement. 

As a result I ended up installing the `modified version of [nexmon-csi](https://github.com/nexmonster/nexmon_csi/tree/pi-5.4.51)` which doesn't support RSSI extraction.

**Comment by Gi-z** [comment]
Thanks for picking this up. The README is long overdue an overhaul and I'm aiming to move things over to a more comprehensive documentation system like sphinx.

Apologies for the issue, I know all too well how long it takes to set up `nexmon_csi` even in the best of circumstances. I'll get the wording there updated and will keep it in mind when writing new docs. Hopefully [T3rO's](https://github.com/T3rO/nexmon_csi_gain) AGC recovery method gets merged in some form in the near future!

**Comment by Gi-z** [comment]
Hopefully that update clears things up a bit. It's my hope that a unified version of the `nexmon_csi` format with all of these features will become available in the near future!

**Comment by CDeLeon94** [comment]
Yeah, that's a little more clear. 

I ended up installing zeroby0's fork, that installer script is much much easier. 
Then I noticed their [pi-5.4.51-plus](https://github.com/nexmonster/nexmon_csi/tree/pi-5.4.51-plus) branch that has support for RSSI and even bakes in some blank space for future data extraction without requiring exiting data to be shifted. 

Might just modify their [python](https://github.com/nexmonster/nexmon_csi/tree/feature/python) branch to decode the `plus` variant of the data. 

Glad to see there are so many people working in this space, though the many active forks and branches is a little overwhelming at times.

**Comment by Gi-z** [comment]
Big fan of Aravind's work for sure. Would recommend finding a solution that fits your area of work best and sticking with it. Constantly changing devices/configurations is a nightmare.

Would suggest taking a look at the scaling method here: https://github.com/Gi-z/CSIKit/blob/master/CSIKit/util/csitools.py#L74
It's based on the method proposed in CRISLoc: https://doi.org/10.1109/JIOT.2020.3022573
I'm hoping to have some work published soon which highlights upsides and downsides to using this approach.

Best of luck in your work, and feel free to let me know if I've missed any other similar issues!
