### ISSUE TITLE
extract the amplitude and phase information of csi from CSV file 

### ISSUE THREAD

**Issue by zhy102** [Gi-z/CSIKit#24]
Thanks for the code, but I only have the CSV file with csi obtained from esp32, I want to extract the amplitude and phase information from it, I can't see it is complex at all from the matrix of CSI_Data, how should I extract them? I'm not familiar with python, I'm good with matlab. thanks!

**Comment by Gi-z** [comment]
Hi, so just like the example, you can load the your CSI data from the ESP32 like so:

`
from CSIKit.reader import CSVBeamformReader
from CSIKit.utils import csitools

reader = CSVBeamformReader()
data = reader.read_file("path/to/your/esp32/csv")
csi_matrix, no_frames, no_subcarriers = csitools.get_CSI(data, metric="amplitude or phase")
`

This will generate your CSI matrix and extract either amplitude or phase depending on the metric you select.
Let me know how that works out for you!

**Comment by zhy102** [comment]
OK， thanks！



---Original---
From: "Glenn ***@***.***&gt;
Date: Sat, Mar 5, 2022 23:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Gi-z/CSIKit] extract the amplitude and phase information of csifrom CSV file  (Issue #24)




 
Hi, so just like the example, you can load the your CSI data from the ESP32 like so:
 from CSIKit.reader import CSVBeamformReader from CSIKit.utils import csitools reader = CSVBeamformReader() data = reader.read_file("path/to/your/esp32/csv") csi_matrix, no_frames, no_subcarriers = csitools.get_CSI(data, metric="amplitude or phase")  
This will generate your CSI matrix and extract either amplitude or phase depending on the metric you select.
 Let me know how that works out for you!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gi-z** [comment]
Oh, and you can also extract the raw complex values by setting `metric=""`.

**Comment by zhy102** [comment]
OK， thank you so much!



---Original---
From: "Glenn ***@***.***&gt;
Date: Sun, Mar 6, 2022 00:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Gi-z/CSIKit] extract the amplitude and phase information of csifrom CSV file  (Issue #24)




 
Oh, and you can also extract the raw complex values by setting metric="".
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
