### ISSUE TITLE
Raw CSI data

### ISSUE THREAD

**Issue by tiyuuu** [Gi-z/CSIKit#30]
How to preprocess raw CSI data? and can be used for further steps for example train and test with ML
I am using ESP32, OS windows

**Comment by Gi-z** [comment]
Hi. The type of preprocessing you should be doing differ based on the application you are trying to implement. If you are looking at published works you should consider the approaches they are using.
An example of a basic preprocessing pipeline is listed in the CSIKit readme [here](https://github.com/Gi-z/CSIKit#using-csi-matrices).

**Comment by ElieCaratge** [comment]
Hello @tiyuuu, i'm interested in the way you collected CSI data. How was organized you setup ? Which devices did you use ?
