### ISSUE TITLE
0 compatible WiFI COTS NICS are found

### ISSUE THREAD

**Issue by TangFang1115** [Gi-z/CSIKit#43]

**Comment by TangFang1115** [comment]
I am using an AX200, the driver has been installed, the network is working normally, but I don't know why it shows that 0 compatible NICS are found

**Comment by Gi-z** [comment]
Unfortunately this issue is with PicoScenes, rather than CSIKit. The PicoScenes issue tracker can be found [here](https://gitlab.com/wifisensing/picoscenes-issue-tracker/-/issues). Hopefully you've managed to resolve this in the meantime.
