### ISSUE TITLE
csikit file_name.pcap error, how to resolve it?csikit file_name.pcap error, how to resolve it?

### ISSUE THREAD

**Issue by sherlock-L-L** [Gi-z/CSIKit#47]
hi, thank you for your csikit.
![1703144478919](https://github.com/Gi-z/CSIKit/assets/154500010/540d61ea-2c3d-41b4-8abd-56f984815e7e)

**Comment by sherlock-L-L** [comment]
I still get an error when I use this command（pip install --upgrade git+https://github.com/Gi-z/CSIKit.git
![1703144781504](https://github.com/Gi-z/CSIKit/assets/154500010/208611dd-c282-44c3-99f0-c4d9aab7f1aa)
）

**Comment by doge0823** [comment]
Hello, now I have the same problem, may I ask you to solve this problem?

**Comment by sherlock-L-L** [comment]
> Hello, now I have the same problem, may I ask you to solve this problem?

I'm sorry, I still haven't resolved this issue

**Comment by doge0823** [comment]
Thanks for your reply, I have successfully implemented it in python. I repeated the two sentences of the author's command two or three times, and then suddenly found that it could be executed.
```
pip uninstall csikit
pip install --upgrade git+https://github.com/Gi-z/CSIKit.git
```

**Comment by sherlock-L-L** [comment]
> 谢谢你的回复，我已经用python成功实现了。我把开发者提供的两条命令重复了两三遍，然后突然发现可以执行了。
> 
> ```
> pip uninstall csikit
> pip install --upgrade git+https://github.com/Gi-z/CSIKit.git
> ```

I repeated it several times, but it didn't work.

**Comment by doge0823** [comment]
May be related to the slow Github network connection, python also shows " fatal: unable to access https:// github.com/gi-z/csikit.git /' ", I suggest that you can try to use VPN software to change the network environment.

**Comment by Gi-z** [comment]
Hi all, sorry for the lack of communication. I've pushed the latest (working!) version of CSIKit (v2.5) to PyPi, so you should be able to update now without using the GitHub option in pip. Let me know if you have any other issues with this and I'd be happy to clear them up. Closing this for now.
