### ISSUE TITLE
 CSI data collection issues

### ISSUE THREAD

**Issue by yjxb1** [Gi-z/CSIKit#48]
I am using a Raspberry Pi (A) to collect CSI data, and keep pinging data to the router through another Raspberry Pi (B). I can collect CSI data, but I don’t know which communication chain the CSI data I collected is. Road data, is this related to the MAC address set by my makecsiparams?
Can anyone answer my question? Thank you so much!

**Comment by Gi-z** [comment]
The MAC address option in `makecsiparams` is used to filter traffic such that the CSI will be recorded only for the specified device. However even if you don't use that option, each frame in the .pcap file is recorded with the MAC address of its source device. This means you can use the `--filter_mac 00:16:ea:etc...` or `read_file(..., filter_mac="00:16:ea:etc...")` options in CSIKit to filter the CSI frames to only those you're interested in. Let me know if you have any other issues with this and I'd be happy to clear them up. Closing this for now.
