### ISSUE TITLE
PicoScenes installation error

### ISSUE THREAD

**Issue by donutthesecond21** [Gi-z/CSIKit#50]
Dear sir,
I hope this message finds you well, I am trying to install picoscenes on Ubuntu 20.04 LTS but the terminal always throws the same error:

dpkg: error processing oackage picoscenes-all (--configure):
 dependancy problems - leaving unconfigured
Sub-process /usr/bin/dpkg returned an error code (1)

same error for picoscenes-plugins-demo-echoprobe-forwarder

Please help me with this,
Thank you

**Comment by Gi-z** [comment]
Unfortunately this issue is with PicoScenes, rather than CSIKit. The PicoScenes issue tracker can be found [here](https://gitlab.com/wifisensing/picoscenes-issue-tracker/-/issues). Hopefully you've managed to resolve this in the meantime.
