### ISSUE TITLE
Dependencies in the setup.py

### ISSUE THREAD

**Issue by ksachdeva** [Gi-z/CSIKit#8]
Thanks, @Gi-z for this interesting work.

At present, your package has hard dependencies on the various libraries (numpy, matplotlib etc) i.e. you require specific versions of them. This is problematic if the user of the package is using either newer versions or older versions of them.

Here is the preferred way to specify the versions -

a) Ideally no version information. This should be the preferred choice.
b) If your package requires a minimum version then use >= 

e.g.
install_requires =
  numpy>=1.19.3
  matplotlib>=3.3.4
  scikit-learn>=0.24.1
  pandas>=1.2.3

or

e.g.
install_requires =
  numpy>=1.19
  matplotlib>=3.3
  scikit-learn>=0.24
  pandas>=1.2

In this one, you are requiring that at a minimum both Major and Minor versions should be respected but it is okay to have a different revision number.

I do not know if you really need these specific versions or any version of numpy, matplotlib... etc is good enough. If that is the case then doing 

install_requires =
  numpy
  matplotlib
  scikit-learn
  pandas

is recommended.

Thanks again for this work; I believe this kind of project will be really helpful to the community.

Regards
Kapil

**Comment by Gi-z** [comment]
Thanks for the issue, I really appreciate pointers like this. I had previously configured the setup.cfg to not use fixed versions, however the incompatibility with a recent-ish numpy version and a Windows build were causing issues which I thought would be best to override. In any case, this is no longer a problem and the fixed versions have now been removed from the dependencies.

Thanks again!
